export const GET_ERRORS = "GET_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const CHANGE_NAVIGATION = "CHANGE_NAVIGATION";
export const GET_ORGANIZATION_USERS = "GET_ORGANIZATION_USERS";
export const CONFIGURE_USER = "CONFIGURE_USER";
export const CONNECT_WIFI_DEVICES = "CONNECT_WIFI_DEVICES"; 
export const SET_ROUTER_URL = "SET_ROUTER_URL";
